#!/bin/php
<?php

/**
 * Simple development CLI for Atmosphere.
 *
 * This script is used to automate common tasks during development. The goal is
 * to make it easy to create new projects, add new modules, etc. The code quality
 * of this script is extremely low, but it's not meant to be used in production.
 *
 * @author Romano Schoonheim <support@atmosphere.sh>
 */

use Symfony\Component\Console\Application;
use Atmosphere\Development\Commands\Quality\CsStyleFixerCommand;
use Atmosphere\Development\Commands\Framework\Generate\CreateFrameworkModule;

require __DIR__ . '/vendor/autoload.php';

$console = new Application('Atmosphere', '1.0.0');

$console->add(new CreateFrameworkModule());
$console->add(new CsStyleFixerCommand());

$console->run();
